### ISSUE TITLE
About Chinese

### ISSUE THREAD

**Issue by qa8306202** [minimaxir/stylecloud#11]
You project seems not to support Chinese. Will you add this function in the future?

**Comment by minimaxir** [comment]
Per the [example in the word_cloud](https://amueller.github.io/word_cloud/auto_examples/wordcloud_cn.html#sphx-glr-auto-examples-wordcloud-cn-py) docs, you need to use a Chinese-supporting font at minimum; it might not work with the default font.

**Comment by qa8306202** [comment]
thank you!
