### ISSUE TITLE
Does not work with jupyter notebooks. 

### ISSUE THREAD

**Issue by avinash-mishra** [minimaxir/stylecloud#12]
I Tried it Today inside Jupyter notebook but it is not working. Could you please check and fix it.

**Comment by minimaxir** [comment]
It outputs `stylecloud.png` to the working directory. To make it appear in a Jupyter notebook, either include it in a Markdown cell.

```md
![](stylecloud.png)
```

Or run this command.

```
from IPython.display import Image
Image(filename='stylecloud.png') 
```

**Comment by avinash-mishra** [comment]
Thanks @minimaxir I'll close the issue.
