### ISSUE TITLE
File Decode Error

### ISSUE THREAD

**Issue by BigtoC** [minimaxir/stylecloud#14]
While I try to read a file contain Chinese: 
> UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 22: character maps to <undefined>

Could you change code in both lines **22** and **27** in _stylecloud.py_ to
`with open(file_path, 'r', encoding="utf8") as f:`

Thanks!

**Comment by minimaxir** [comment]
Fixed in https://github.com/minimaxir/stylecloud/commit/15b7c54d5400e7a24ea08e518a68673b9301301f, and version `0.4.1` pushed.

**Comment by minimaxir** [comment]
Rather fixed for real in 0.4.2
