### ISSUE TITLE
An error was reported on imported StyleCloud version 0.5.1

### ISSUE THREAD

**Issue by aiaiduo** [minimaxir/stylecloud#22]
My Python version 3.8.9 ,StyleCloud version is 0.5.1. When I imported StyleCloud, the error information is as follows. Please help me to find out what the problem is. Thks!

![Snipaste_2021-04-11_09-29-38](https://user-images.githubusercontent.com/28044296/114289200-887cde00-9aa8-11eb-91e8-b4f992ad3121.png)

**Comment by Rachit-Singh** [comment]
Same is happening for me as well. My python version is 3.9.4. 
![Screenshot 2021-04-22 225439](https://user-images.githubusercontent.com/51758870/115759680-26807a80-a3be-11eb-96c2-77aaa13fca3e.jpg)

**Comment by armanivvv** [comment]
Works by downgrading matplotlib to 3.2.2

**Comment by minimaxir** [comment]
I just pushed out v0.5.2 which removes `makeMappingArray` and replaces it with a more correct implementation. Let me know if that works!

**Comment by Rachit-Singh** [comment]
Thanks for the update. It works like a charm now.
